#
# SITE SETTINGS
#

# base of your site relative to the root of the Web site, eg / or ""
baseurl: ""
# URL of your site, eg https://cfrioux.github.io
url: "https://snmendoz.github.io"

# site information
title: Sebastián Mendoza
pronounsfirst: he
pronounssecond: his
description: > # this means to ignore newlines until the next tag
  Research scientist
  Center For Mathematical Modeling
  Santiago, Chile
author: Sebastián Mendoza
blog_dir: /blog
permalink: /blog/posts/:year/:month/:day/:title/ # prefixed style
category_dir: /blog/categories/
category_title_prefix: "category: "

# author information
picture: https://static.mamot.fr/accounts/avatars/000/032/478/original/1820a2afa24757a2.jpeg
email: (firstname).(lastname)@inria.fr
networks:
  # twitter:
  #   url: https://twitter.com/
  #   username: snmendoz
  github:
    url: https://github.com/
    username: snmendoz
  linkedin:
    url: https://www.linkedin.com/
    username: in/snmendoz
  scholar:
    url: https://scholar.google.com/citations?user=
    username: 3rDvuGcAAAAJ
  orcid:
    url: https://orcid.org/
    username: 0000-0002-2192-5569

# contacts
contacts:
  research:
    email: smendoza@cmm.uchile.cl
    address: >
      Beauchef 851t<br/>
      Santiago<br/>
      Chile
    # direction:
    #   map: https://www.openstreetmap.org/way/182389279
    #   public_transportation:
    #     stop:
    #     link:

# research
research:
  presentation:
    overview: true
    thesis: false
    publications: true
    software: true
    posters: true
  restriction:
      publications: 10
      latest: 2
  restrictionNews:
      news: 5
      latest: 1

# apparence of posts

# apparence of buttons
link_btn_size: btn-xs
link_btn_color: btn-primary
publications_btn_size: btn-xs
publications_btn_color: btn-default
publications_btn_textcolor: text-primary

# alerts
alerts:
  no-javascript:
    danger: true
    warning: true
    information:  true

# bibliography
kind:
  label: pp_kind # label used in .bib files to denote the kind (international/national) of references
  separate:  # should international/national references be separated: (true | false)
    article: false
    inbook: false
    inproceedings: false


scholar:
  style: _bibliography/mystyle.csl
  locale: en
  sort_by: year, pp_rank
  order: descending
  group_by: none
  group_order: ascending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  bibtex_skip_fields: [pp_shortbooktitle, pp_rank, pp_kind]
  # details_dir:    bibliography
  # details_layout: bibtex.html
  # details_link:   Details
  query: "@*"

# other settings
exclude:  ['Gemfile*', '*.sh', 'update_site.sh', 'vendor']
plugins:
  - jekyll-scholar
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem]
markdown: kramdown
highlighter: rouge
kramdown:
     # input: GFM
     syntax_highlighter: rouge
